### ISSUE TITLE
"fire beam errors = scorching ray crashes client"

### ISSUE THREAD

**Issue by Soruja** [vmv/PoeSmoother#4]
was this fixed in the most recent update? if not id like to know what im removing to stop ticking it to it wont affect it cause ill be trying to rush people and then they use scorching ray and my client crashes

removing sound and others dealing with critters causes the game to crash with 
"critters need actor component"
dx9 32bit path of exile version

**Comment by VergilUa** [comment]
From what I've tested these options do not cause any firebeam problems:
- breach
- particles
- gore
- corpe exp fx
- mtx
- fog & shadows

Haven't used other options, but most likely it is remove other/remove sounds issue. Vmv might wanna look into this, since I'm not sure what and how modified in other options.

**Comment by Soruja** [comment]
i always keep a backup. saves data. just takes me 6 mins to make a new backup lol

**Comment by vmv** [comment]
I'm 99% sure that i have fixed critters error and updated the release. I forgot what it was...:|
