### ISSUE TITLE
resolving metadata with new parakeet pet

### ISSUE THREAD

**Issue by Soruja** [vmv/PoeSmoother#8]
god dammit vonderhar

"":resolving metadata/critters/swallow/nestloop/fly3 failed
its the sounds option for effect sounds and pets and stuff

:( why vmv... why -crys-

offtopic: idk how it happened last time but none of the effect changes from smoother do it this time compared to last poesmoother version.

before the most current fixes you did, when i ran the game it would hide my shield completely as if i didnt have a shield at all. (yakasha shield mtx) is there anyway you can make it so we can have the option to hide our shield and sword intentionally with the smoother (completely unarmed)? 

so then my character will no longer have a weapon nor a offhand. if not id understand. thanks

**Comment by VergilUa** [comment]
Answer to your offtopic:
I bet the shield was just invisible. So to make character fully unarmed you need to have at least one mtx that modifies wep/wep, 2h wep, wep/shield, and then just modify that mtx'es.

Otherwise it would require to modify current equiped items, which would require to read memory to do so. So the answer is probably no.

**Comment by Soruja** [comment]
alright. well ty for the reply. hope the parakeet thing helped though
